"""
Django settings for SocialMedia project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from sshtunnel import SSHTunnelForwarder
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pr3kt&gk36x+b)!orjq!gi)l8b8%-%j#hrkz3&hw)fd=9t2(8#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'channels',
    'daphne',
    'user_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home_app',
    'posts_app',
    'chat_app',
    'profile_app'
]
AUTH_USER_MODEL = 'user_app.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SocialMedia.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 
            BASE_DIR / 'templates',
            BASE_DIR / 'home_app/templates',
            BASE_DIR / 'profile_app/templates',
            BASE_DIR / 'posts_app/templates',
            BASE_DIR / 'user_app/templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chat_app.context_processors.sidebar_chats_processor', 
            ],
        },
    },
]

WSGI_APPLICATION = 'SocialMedia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# server = SSHTunnelForwarder(
#    ('ssh.pythonanywhere.com', 22),      
#    ssh_username='WorldITSocialNetwork', 
#    ssh_password='oL4qhR8vzO9p',      
#     remote_bind_address=('WorldITSocialNetwork-5274.postgres.pythonanywhere-services.com', 15274) 
# )
# server.start()
DATABASES = {
     'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'data',
#        'USER': 'super',
#        'PASSWORD': 'kC9gN3bqA',
#        'HOST': '127.0.0.1',
#        'PORT': str(server.local_bind_port),
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
     }    
}
# from django.db.backends.base.base import BaseDatabaseWrapper
# BaseDatabaseWrapper.check_database_version_supported = lambda self: None
        
        #sqlite3
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        
        #'ENGINE': 'django.db.backends.postgresql',
        #'NAME': 'data',
        #'USER': 'data',
        #'PASSWORD': 'kC9gN3bqA',
        #'HOST': 'WorldITSocialNetwork-5274.postgres.pythonanywhere-services.com',
        #'PORT': '15274'
#postgresql://data:kC9gN3bqA@ WorldITSocialNetwork-5274.postgres.pythonanywhere-services.com:15274/data

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ 
    BASE_DIR / 'static',
    BASE_DIR / 'home_app/static',
    BASE_DIR / 'profile_app/static',
    BASE_DIR / 'posts_app/static',
    BASE_DIR / 'user_app/static',
    BASE_DIR / 'chat_app/static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'potapenkoarina700@gmail.com'
EMAIL_HOST_PASSWORD = 'pxke odym mmjf elqs' 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ASGI_APPLICATION = 'SocialMedia.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}