# Generated by Django 6.0.3 on 2026-06-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post_app_post',
        ),
    ]
