# Generated by Django 6.0.3 on 2026-06-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postheart',
            table='post_app_postheart',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_app_postimage',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='post_app_postlike',
        ),
        migrations.AlterModelTable(
            name='postlink',
            table='post_app_postlink',
        ),
        migrations.AlterModelTable(
            name='postview',
            table='post_app_postview',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='post_app_post_tag',
        ),
    ]
