# Generated by Django 6.0.3 on 2026-06-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_alter_postheart_table_alter_postimage_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='post_app_tag',
        ),
    ]
